# 第4章 線形単回帰モデルの推定と検定 {-#ch4}
先に[出版社サイト](https://www.yuhikaku.co.jp/books/detail/9784641053854)よりデータをダウンロードする.
```{r collapse=T, eval=FALSE}
# サポートファイルへのリンク
curl <- "https://www.yuhikaku.co.jp/static_files/05385_support04.zip"
# ダウンロード保存用フォルダが存在しない場合, 作成
if(!dir.exists("downloads")){
    dir.create("downloads")
}
cdestfile <- "downloads/support04.zip"
download.file(curl, cdestfile)
# データ保存用フォルダが存在しない場合, 作成
if(!dir.exists("data")){
    dir.create("data")
}
# WSL上のRで解凍すると文字化けするので、Linuxのコマンドを外部呼び出し
# Windowsの場合は別途コマンドを用いる.
if(.Platform$OS.type == "unix") {
    system(sprintf('unzip -n -Ocp932 %s -d %s', "downloads/support04.zip", "./data"))
} else {
    print("Windowsで解凍するコマンドを別途追加せよ.")
}
```

必要なライブラリを読み込む.
```{r collapse=T}
library(tidyverse)
library(openxlsx) # Excelファイルを読み取るためのパッケージ
```
## 練習問題 4-1 [確認] {-}

## 練習問題 4-2 [実証] {-}

## 練習問題 4-3 [確認] {-}

## 練習問題 4-4 [確認] {-}

## 練習問題 4-5 [確認] {-}

## 練習問題 4-6 [確認] {-}

## 練習問題 4-7 [確認] {-}

## 練習問題 4-8 [発展] {-}

## 練習問題 4-9 [発展] {-}

## 練習問題 4-10 [実証] {-}
