# 第5章 重回帰モデルの推定と検定 {#ch5 .unnumbered}

先に[出版社サイト](https://www.yuhikaku.co.jp/books/detail/9784641053854)よりデータをダウンロードする.

```{r collapse=T}
# サポートファイルへのリンク
curl <- "https://www.yuhikaku.co.jp/static_files/05385_support05.zip"
# ダウンロード保存用フォルダが存在しない場合, 作成
if(!dir.exists("downloads")){
    dir.create("downloads")
}
cdestfile <- "downloads/support05.zip"
download.file(curl, cdestfile)
# データ保存用フォルダが存在しない場合, 作成
if(!dir.exists("data")){
    dir.create("data")
}
# WSL上のRで解凍すると文字化けするので、Linuxのコマンドを外部呼び出し
# Windowsの場合は別途コマンドを用いる.
if(.Platform$OS.type == "unix") {
    system(sprintf('unzip -Ocp932 %s -d %s', "downloads/support05.zip", "./data"))
} else {
    print("Windowsで解凍するコマンドを別途追加せよ.")
}
```

必要なライブラリを読み込む.

```{r collapse=T}
library(tidyverse)
```

## 練習問題 5-1 [確認] {.unnumbered}

## 練習問題 5-2 [確認] {.unnumbered}

## 練習問題 5-3 [確認] {.unnumbered}

## 練習問題 5-4 [確認] {.unnumbered}

## 練習問題 5-5 [確認] {.unnumbered}

## 練習問題 5-6 [確認] {.unnumbered}

## 練習問題 5-7 [確認] {.unnumbered}

## 練習問題 5-8 [確認] {.unnumbered}

## 練習問題 5-9 [確認] {.unnumbered}

## 練習問題 5-10 [発展] {.unnumbered}

## 練習問題 5-11 [発展] {.unnumbered}

## 練習問題 5-12 [発展] {.unnumbered}

## 練習問題 5-13 [\*発展] {.unnumbered}

## 練習問題 5-14 [実証] {.unnumbered}

## 練習問題 5-15 [実証] {.unnumbered}
